version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run: 
          name: Generate Dependency File
          command: |
            mkdir -p workspace
            mvn dependency:tree -DoutputFile=workspace/maven_dep_tree.txt
            cat workspace/maven_dep_tree.txt
      - persist_to_workspace: 
          root: workspace 
          paths:
            - maven_dep_tree.txt

  scan:
    docker:
      - image: returntocorp/semgrep
    steps:
      - checkout
      - attach_workspace: # This step attaches the workspace from the previous job
          at: /tmp/workspace
      - run: 
         name: Semgrep full scan
         command: |
           cp /tmp/workspace/maven_dep_tree.txt .
           semgrep ci
         
workflows:
  version: 2
  build_and_scan:
    jobs:
      - build
      - scan:
          context:
            - semgrep
          requires:
            - build
