version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run: 
          name: Generate Dependency File
          command: |
            mkdir target
            mvn dependency:tree -DoutputFile=target/maven_dep_tree.txt
      - persist_to_workspace: 
          root: . 
          paths:
            - target 

  scan:
    docker:
      - image: returntocorp/semgrep
    steps:
      - checkout
      - run: 
         name: Semgrep full scan
         command: semgrep ci 
         
workflows:
  version: 2
  build_and_scan:
    jobs:
      - build
      - scan:
          context:
            - semgrep
          requires:
            - build
