version: 2.1
workflows:
  semgrep:
    jobs:
      - semgrep-full-scan:
          filters:
            branches:
              only: main
          context:
            - semgrep
      - semgrep-diff-scan:
          filters:
            branches:
              ignore: main
          context:
            - semgrep
jobs:
  semgrep-full-scan:
    docker:
      - image: returntocorp/semgrep
    steps:
      - checkout
      - run:
          name: "Semgrep full scan"
          command: |
            semgrep ci
  semgrep-diff-scan:
    parameters:
      default_branch:
        type: string
        default: main
    docker:
      - image: returntocorp/semgrep
    steps:
      - checkout
      - run: 
          name: Semgrep diff scan
          environment: 
            SEMGREP_BASELINE_REF: << parameters.default_branch >>
          command: |
            echo "Running semgrep and dumping results to JSON file"
            export SEMGREP_BASELINE_REF="origin/main"
            export SEMGREP_COMMIT=$CIRCLE_SHA1
            export SEMGREP_JOB_URL=$CIRCLE_BUILD_URL
            git fetch origin "+refs/heads/*:refs/remotes/origin/*"
            semgrep ci --baseline-commit=$(git merge-base main HEAD) 
